version: '3.6'

services:


  web:
    image: nginx
    container_name: income-tracker-web
    restart: always
    volumes:
      - "./app:/var/www/html"
      - "./web/nginx:/etc/nginx/"
    ports:
      - "8080:80"


  php:
    image: php:7.2-fpm
    container_name: income-tracker-php
    build:
      context: ./
      dockerfile: php.dockerfile
    volumes:
      - "./app:/var/www/html"

  mysql:
    image: mysql:5.7
    container_name: income-tracker-db
    restart: always
    volumes:
      - ./db:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 1cVQdaC3SSM21Xl
      MYSQL_DATABASE: income_tracker

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: income-tracker-pma
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1cVQdaC3SSM21Xl
      - PMA_HOST=income-tracker-db
    ports:
      - "9000:80"
