version: '3.6'

services:

  # app:
  #   build:
  #     context: ./
  #     dockerfile: app.dockerfile
  #   container_name: income-tracker-app
  #   restart: always
  #   volumes:
  #     - "./app:/var/www"

  web:
    image: php:7.2-apache
    build:
      context: ./
      dockerfile: web.dockerfile
    container_name: income-tracker-web
    restart: always
    volumes:
      - "./web/apache2:/etc/apache2"
      - "./app:/var/www/html"
    ports:
      - "8080:80"


  mysql:
    image: mysql:5.7
    container_name: income-tracker-db
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1cVQdaC3SSM21Xl
      MYSQL_DATABASE: income_tracker

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: income-tracker-pma
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1cVQdaC3SSM21Xl
      - PMA_HOST=income-tracker-db
    ports:
      - "9000:80"
